### PR TITLE
switch background animation to requestAnimFrame

### PR DESCRIPTION
**Pull request by alexanderbuhler**
The neat background animation was taking >30% GPU (RTX 2070) even when the tab was minimized so I thought I'll try and rebuild this with requestAnimationFrame. Limited to 30 fps it now sits at 2-3% GPU and only if the tab is active.

Have never touched React before so please have a look whether this code makes sense and doesn't break stuff 😉 

P.S.: Thanks for the awesome reads on your blog!

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Hey @alexanderbuhler, you are great! I will check your code in the next days and give you feedback.

**Comment by fabian-hiller** [comment]
Hey @alexanderbuhler I'm very sorry I didn't get around to checking your code until now. You're right, the current animation is performant since it's rendered using the GPU, but also performance intensive since the browser tries to refresh the screen 60 times per second, which is not mandatory in this case. Your idea with `requestAnimationFrame()` is interesting and also seems to be the right choice on the fly to control the refresh rate.

Here's some feedback I have on your implementation. The only thing the animation basically does is change the opacity. Generating the background with the `updateBackground()` function is not part of the animation. Accordingly, I would use the CSS property `opacity` for this and not the opacity of the color code. This also has the advantage that the background does not have to be regenerated with every frame.

What do you think about the suggestion to remove my Tailwind CSS animation just like in your code, but keep the rest of it and then control the animation with `requestAnimationFrame()` and the CSS property `opacity` in a separate `useEffect()` hook? In doing so, we could use a reference to access the `style` object of the HTML element, thus preventing React from having to re-render the component on every frame. If you're interested, I'll leave the implementation to you. Otherwise, I would try my hand at it. Thanks again for your attention!

**Comment by alexanderbuhler** [comment]
Hey @fabian-hiller thank you very much for reviewing. Appreciate your feedback. 

The reason I went for color animation here is I remembered animating opacity by itself was quite inefficient some time ago. Might have changed today since following data is also quite outdated. Also it doesn't really represent a "related" setup compared to our situation. https://stackoverflow.com/questions/38523826/text-css-rendering-performance-rgba-vs-hex-vs-opacity

I've pushed another version limiting the animation to opacity only. GPU usage is rougly the same at ~3%.

I reverted the color randomization you previously had, however kept my refactoring of background settings.

Feel free to adjust as you see fit :-)

Did React really re-render the whole component just because a style property was being updated or where does this come from?

**Comment by fabian-hiller** [comment]
> Did React really re-render the whole component just because a style property was being updated or where does this come from?

React re-renders a component if its state or properties change. If you access an HTML element directly by reference, the component is not re-rendered.

A few improvements I would like to do before I merge your code into the `main` branch. What is the best way to do this? Do I need to create a pull request on your fork?

**Comment by alexanderbuhler** [comment]
Thanks for the insight! Sure, based on what I'm reading out of this tooltip, you should be able to directly write to the branch on my forked repo, hence adding ontop of the commits in the pull request.

**Comment by fabian-hiller** [comment]
Thank you @alexanderbuhler. I have a lot to do at the moment, so unfortunately I won't get to it until the weekend or next week. I apologize for this.

**Comment by fabian-hiller** [comment]
Sorry again that I can only work on the PR irregularly. My schedule does not allow me to do otherwise at the moment. I did decide to give you feedback again and make changes to the code only in consultation with you.

I would remove the `backgroundRenderingSettings` object, since no property is used in different places, it makes the rest of the code more unclear and increases the bundle size. Also, for better clarity, I would write all the code that affects the opacity animation in the `useEffect()` hook and remove the `updateBackgroundOpacity()` function since it is only called in a single place and write the code directly in the `animateBackgroundOpacity()` function. This could also allow us to remove the `useRef()` hook and keep the value of the return from `requestAnimationFrame()` inside the `useEffect()` hook. Also, I would write a short comment as an explanation above the `useEffect()` hook.

Let me know if you disagree or if I missed something. I want to try to keep the code as simple, consistent, and minimal as possible.

**Comment by alexanderbuhler** [comment]
No worries. Appreciate you checking in on that. Guess I made a habit of explicitly extracting any piece that might be reused by other things even though in this case indeed there probably won't be the case of it being used more than once. Also my intention behind splitting `update` and `animate` is solely based on separating concerns.

I'm fine with your suggestions. Thanks for the heads up!

**Comment by fabian-hiller** [comment]
Do you want to make the changes or do you want me to do it?

**Comment by alexanderbuhler** [comment]
I was hoping for you to complete the implementation as suggested, if you don’t mind :)

**Comment by fabian-hiller** [comment]
Hey @alexanderbuhler, I'm on vacation at the moment. Therefore, no reaction came from me so far. I will do it as soon as I get back.

**Comment by fabian-hiller** [comment]
Hey @alexanderbuhler, I have now implemented the changes. Also, I have been studying the performance of different implementations for quite a while. In the end I was able to achieve the lowest bundle size with the same performance with `setInterval()`. I know that `setInterval()` is not recommended for animations. But I think it makes no difference for this small animation. If you are interested you can compare the performance between your implementation on your computer and give me feedback.

**Pull request merged**
